const timezones = [
    { offset: 'GMT-12:00', location: 'Baker Island' },
    { offset: 'GMT-11:00', location: 'American Samoa' },
    { offset: 'GMT-10:00', location: 'Hawaii' },
    { offset: 'GMT-09:00', location: 'Alaska' },
    { offset: 'GMT-08:00', location: 'Los Angeles' },
    { offset: 'GMT-07:00', location: 'Denver' },
    { offset: 'GMT-06:00', location: 'Chicago' },
    { offset: 'GMT-05:00', location: 'New York' },
    { offset: 'GMT-04:00', location: 'Atlantic Time (Halifax)' },
    { offset: 'GMT-03:00', location: 'Buenos Aires' },
    { offset: 'GMT-02:00', location: 'South Georgia' },
    { offset: 'GMT-01:00', location: 'Azores' },
    { offset: 'GMT+00:00', location: 'London' },
    { offset: 'GMT+01:00', location: 'Berlin' },
    { offset: 'GMT+02:00', location: 'Cairo' },
    { offset: 'GMT+03:00', location: 'Moscow' },
    { offset: 'GMT+03:30', location: 'Tehran' },
    { offset: 'GMT+04:00', location: 'Dubai' },
    { offset: 'GMT+04:30', location: 'Kabul' },
    { offset: 'GMT+05:00', location: 'Islamabad' },
    { offset: 'GMT+05:30', location: 'Mumbai' },
    { offset: 'GMT+05:45', location: 'Kathmandu' },
    { offset: 'GMT+06:00', location: 'Dhaka' },
    { offset: 'GMT+06:30', location: 'Cocos Islands' },
    { offset: 'GMT+07:00', location: 'Bangkok' },
    { offset: 'GMT+08:00', location: 'Beijing' },
    { offset: 'GMT+09:00', location: 'Tokyo' },
    { offset: 'GMT+09:30', location: 'Adelaide' },
    { offset: 'GMT+10:00', location: 'Sydney' },
    { offset: 'GMT+10:30', location: 'Lord Howe Island' },
    { offset: 'GMT+11:00', location: 'Magadan' },
    { offset: 'GMT+12:00', location: 'Fiji' },
    { offset: 'GMT+13:00', location: 'Tonga' },
    { offset: 'GMT+14:00', location: 'Line Islands' },
];

export default timezones;
